// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10_EF_LifeCycleTrackingSeedData.Context;

#nullable disable

namespace _10_EF_LifeCycleTrackingSeedData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_10_EF_LifeCycleTrackingSeedData.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "William",
                            LastName = "Shaksper"
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = "Fyoder",
                            LastName = "Dostoyevski"
                        });
                });

            modelBuilder.Entity("_10_EF_LifeCycleTrackingSeedData.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorID = 1,
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorID = 1,
                            Title = "Karamazoz Kardeşler"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorID = 2,
                            Title = "Yeraltından Notlar"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorID = 2,
                            Title = "Beyaz Cüceler"
                        });
                });

            modelBuilder.Entity("_10_EF_LifeCycleTrackingSeedData.Models.Book", b =>
                {
                    b.HasOne("_10_EF_LifeCycleTrackingSeedData.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("_10_EF_LifeCycleTrackingSeedData.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
